# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /var/www/imx-buy-bot
            git pull git@github.com:SunnyBenji/imx-buy-bot.git
            pm2 delete all
            pm2 start "yarn -s buy-eth >> ~/logs/buy-eth.log"
            pm2 start "yarn -s buy-imx >> ~/logs/buy-imx.log
            pm2 start "yarn -s buy-usdc >> ~/logs/buy-usdc.log
            echo "Deploy ok"
